projectcapsule/capsule

- Makefile
- cmd/manager/main.go
- pkg/controller/namespace/namespace_controller.go
- pkg/controller/secret/reconciler.go
- pkg/indexer/indexer.go
- pkg/webhook/network_policies/validating.go
- pkg/webhook/owner_reference/patching.go
- pkg/webhook/webhook.go
Closes #12 with minor coding style improvements.
> Implementing Capsule Tenant ownership predicate for Namespace Controller

- deploy/mutatingwebhookconfiguration.yaml
- pkg/controller/tenant/tenant_controller.go
Closes #14: the hotfix works but still a draft to improve the code-base.
> Fixing the ResourceQuota update

- README.md
- contributing.md
Closes #16.
Please, @bsctl review.
> Providing contributing documentation

- Makefile
- controllers/tenant_controller.go
> Adding exists requirement to avoid pruning tenant owner resources

- api/v1alpha1/tenant_annotations.go
- controllers/tenant_controller.go
- go.mod
- go.sum
> Syncing Namespace annotations for Storage and Ingress classes

- Makefile
- README.md
Although removing Capsule could be sad (:crying_cat_face:)  this PR closes #31
> Enabling Capsule removal and documenting it

- api/v1alpha1/tenant_types.go
- config/crd/bases/capsule.clastix.io_tenants.yaml
Closes #26 
```
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER   AGE
oil    3                 0                 alice   5m27s
```
> Adding additional printer columns

- controllers/namespace_controller.go
This is going to fix bug introduced by a3c667b
> Updating tenant after adding/removing Namespace

- api/v1alpha1/tenant_types.go
- config/crd/bases/capsule.clastix.io_tenants.yaml
Closes #28.
```
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER   AGE
oil    3                 1                 alice   13h
```
> Providing shortName tnt for Tenant

- README.md
- contributing.md
- use_cases.md
> Updating docs

- controllers/tenant_controller.go
> Ignoring NotIn requirement during resource pruning

- main.go
Closes #55.
@bsctl feel free to merge this once reviewed.
> Adding probes

- pkg/webhook/ingress/validating.go
- pkg/webhook/namespace_quota/validating.go
- pkg/webhook/network_policies/validating.go
- pkg/webhook/owner_reference/patching.go
- pkg/webhook/pvc/validating.go
- pkg/webhook/service_labels/patching.go
- pkg/webhook/tenant_prefix/patching.go
- pkg/webhook/utils/in_capsule_group.go
> Using pointers and internal handler for Namespace OwnerReferences

- README.md
- contributing.md
- controllers/rbac/const.go
- controllers/tenant_controller.go
- e2e/suite_test.go
- e2e/utils_test.go
- use_cases.md
> Making CR/CRB names conforming to Kubernetes naming requirements

- pkg/webhook/ingress/validating.go
> Fix null pointer exception in Ingress validating webhook

- config/samples/capsule_v1alpha1_tenant.yaml
Closes #96, introduced with PR #89 (/cc @MaxFedotov).
No need for a new release since it's just a matter of documentation.
> Adding StorageClassesSpec and IngressClassesSpec to Tenant example

- Makefile
> Removing CR/B upon Capsule removal

- .github/workflows/main.yml
- Makefile
- e2e/ingress_class_test.go
- e2e/service_metadata_test.go
- e2e/utils_test.go
- pkg/webhook/service_labels/patching.go
- pkg/webhook/service_labels/types.go
> Using matrix strategy for e2e on multiple k8s versions

- pkg/webhook/tenant_prefix/patching.go
Closes #117, just a simple code enhancement, no side effects are expected.
> Duplicated code, can be easily removed

- README.md
@prometherion temporary fix of #125. There are needs to improve and update all the documentation. Planning to do in short time.
> update README with Helm installation method

- Makefile
- config/manager/kustomization.yaml
> Using latest current version rather than latest tag

- e2e/force_tenant_prefix_test.go
- e2e/utils_test.go
- pkg/webhook/owner_reference/patching.go
- pkg/webhook/tenant_prefix/validating.go
> Enforcing back tenant selection using closest match for namespace prefix

- .github/workflows/main.yml
- config/manager/kustomization.yaml
Further details: [engineerd/setup-kind@v0.5.0](https://github.com/engineerd/setup-kind/releases/tag/v0.5.0)
> Upgrading GitHub actions

- .github/workflows/main.yml
- Dockerfile
- Makefile
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- main.go
- version.go
> Bumping Makefile to v0.0.2 and minor hotfix on Kustomize

- pkg/webhook/ingress/errors.go
- pkg/webhook/ingress/validating.go
- pkg/webhook/pvc/errors.go
- pkg/webhook/pvc/validating.go
> Provide a more meaningful error message when not admitted Storage/Ingress Classes are used

- config/manager/kustomization.yaml
Once merged, going to prepare the GH release.
> Releasing v0.0.3

- charts/capsule/README.md
> Updating Helm instructions

- api/v1alpha1/tenant_annotations.go
- controllers/tenant_controller.go
- use_cases.md
Closes #152.
`use_case.md` file has been updated, too. No need for tests here since quite useless for an e2e scenario.
> Annotating ResourceQuota with Hard quota

- charts/capsule/Chart.yaml
- charts/capsule/templates/_helpers.tpl
- charts/capsule/templates/ca.yaml
- charts/capsule/templates/certs.yaml
- charts/capsule/templates/deployment.yaml
- charts/capsule/templates/post-install-job.yaml
- charts/capsule/templates/pre-delete-job.yaml
Closes #155.
Secret resources are going to be created only at installation and removed using the pre-delete hook thas has been improved as the post-install one.
> Enhancing Helm Chart lifecycle

- controllers/secret/ca.go
- controllers/tenant_controller.go
- e2e/namespace_capsule_label_test.go
- go.mod
- go.sum
> No loop on ResourceQuota outer updates and error handling improvements

- e2e/additional_role_bindings_test.go
- e2e/allowed_external_ips_test.go
- e2e/container_registry_test.go
- e2e/custom_capsule_group_test.go
- e2e/force_tenant_prefix_test.go
- e2e/ingress_class_test.go
- e2e/missing_tenant_test.go
- e2e/namespace_capsule_label_test.go
- e2e/namespace_metadata_test.go
- e2e/new_namespace_test.go
- e2e/overquota_namespace_test.go
- e2e/owner_webhooks_test.go
- e2e/protected_namespace_regex_test.go
- e2e/resource_quota_exceeded_test.go
- e2e/selecting_non_owned_tenant_test.go
- e2e/selecting_tenant_fail_test.go
- e2e/selecting_tenant_with_label_test.go
- e2e/service_metadata_test.go
- e2e/storage_class_test.go
- e2e/tenant_name_webhook_test.go
- e2e/tenant_owner_group_test.go
- e2e/tenant_resources_changes_test.go
- e2e/tenant_resources_test.go
> Eventually refactoring and minor fixes

- .github/workflows/e2e.yml
> Adding k8s 1.20 to E2E testing matrix

- e2e/namespace_metadata_test.go
Related to #172, missed these changes.
> Letting tests to accept eventually value, rather than strict expectation

- controllers/tenant_controller.go
I came across this after  watching the video presentation. This is
just a it pick. I hope to play around with this soon.
```
if err != nil {
return err
}
return nil
```
Is the same as
```
return err
```
> Short circuit error returns

- pkg/utils/user_group.go
- pkg/utils/user_group_test.go
> IsInCapsuleGroup binary search is case-sensitive broken

- charts/capsule/Chart.yaml
- charts/capsule/crds/tenant-crd.yaml
[v0.0.4](https://github.com/clastix/capsule/releases/tag/v0.0.4) is here
> Updating Helm Chart to to v0.0.4 release

- Makefile
- charts/capsule/Chart.yaml
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
> Non preserving CRD unknown fields

- config/manager/kustomization.yaml
- e2e/ingress_hostnames_test.go
- pkg/webhook/ingress/validating.go
Closes #184.
@bsctl may I ask you a review? Tested locally and it works for me.
> Fixing the IngressClass return logic breaking Hostnames check

- charts/capsule/Chart.yaml
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- config/webhook/manifests.yaml
- pkg/webhook/tenant/validating.go
> Validating Tenant also on UPDATE

- charts/capsule/Chart.yaml
- charts/capsule/templates/ca.yaml
- charts/capsule/templates/certs.yaml
> Avoiding Capsule secrets deletion on Helm upgrade

- README.md
- docs/index.md
- docs/operator/use-cases/create-namespaces.md
- docs/operator/use-cases/custom-resources.md
- docs/operator/use-cases/images-registries.md
- docs/operator/use-cases/ingress-classes.md
- docs/operator/use-cases/ingress-hostnames.md
- docs/operator/use-cases/multiple-tenants.md
- docs/operator/use-cases/nodes-pool.md
- docs/operator/use-cases/onboarding.md
- docs/operator/use-cases/overview.md
- docs/operator/use-cases/permissions.md
- docs/operator/use-cases/resources-quota-limits.md
- docs/operator/use-cases/storage-classes.md
Lets merge went thru the use-cases and updated many mistakes
> Documentation Spelling Mistakes #197

- docs/operator/use-cases/create-namespaces.md
- docs/operator/use-cases/network-policies.md
- pkg/webhook/namespacequota/errors.go
- pkg/webhook/networkpolicies/validating.go
- pkg/webhook/ownerreference/patching.go
- pkg/webhook/tenantprefix/validating.go
Noticed a typographical error in the output while testing. This should clear it up.
> fixing a typo that is somewhat pervasive

- controllers/tenant_controller.go
Closes #200.
This is fixing the dysfunctional previous behavior: the Tenant Owner was able to create a Namespace along with specific annotations and labels and this is a wrong assumption since this task must be in charge of the Cluster Admin designing the Tenant isolation (e.g. adding Velero labels or other vendor-specific annotations that are not managed by Capsule itself).
> Namespace metadata are just controlled by the Tenant manifest

- Makefile
- charts/capsule/Chart.yaml
- charts/capsule/README.md
- charts/capsule/templates/deployment.yaml
- charts/capsule/values.yaml
- e2e/tenant_resources_test.go
> Capsule Deployment probes are configurable through Helm values

- controllers/tenant_controller.go
Closes #226.
This was leading to enqueuing back several reconciliation requests, causing a cascading loop-effect.
`syncNamespaceMetadata` function will handle everything that is needed for the Namespace resource, as additional metadata as the scheduler one for the node-selector.
> Namespaces annotations must be managed in a single update function

- hack/create-user-openshift.sh
Issue #229
Added hack/create-user-openshift.sh for creating a demo user and tenant on OCP
> add: User script for Openshift (tested on OCP 4.7.1)

- charts/capsule/Chart.yaml
- charts/capsule/README.md
- charts/capsule/templates/deployment.yaml
- charts/capsule/values.yaml
Tnx to @davideimola and @prometherion  for the help!
Closes #232
> Remove options allow-ingress-hostname-collision and allow-tenant-ingress-hostnames-collision, solve #232

- controllers/tenant_controller.go
Hi there!
I've created this issue explaining this PR with words and the use-case I'm trying to solve: #241 
In short, I would like to include a label called "name" (or any other suggested key) per Namespace, so I can reference them in NetworkPolicies.
> Add name label to each Namespace

- .github/workflows/helm.yml
> chore: triggering Helm Charts CD upon tag release

- docs/proxy/overview.md
- docs/proxy/sidecar.md
> update capsule-proxy documentation

- e2e/disable_node_ports_test.go
- e2e/enable_node_ports_test.go
- pkg/webhook/services/errors.go
- pkg/webhook/services/validating.go
> feat: block use of NodePort Services

- controllers/secret/tls.go
> Webhook certificate TLS DNS name matches the deployed namespace

- .github/workflows/ci.yml
- Makefile
- charts/capsule/templates/pre-delete-job.yaml
- controllers/rbac/manager.go
- e2e/custom_capsule_group_test.go
- e2e/utils_test.go
- go.mod
- main.go
- pkg/utils/user_group.go
- pkg/utils/user_group_test.go
- pkg/webhook/utils/in_capsule_groups.go
> feat: use multiple groups as capsule-user-group

- pkg/webhook/services/validating.go
> fix: wrong order of checks in validating-external-service-ips webhook

- controllers/rbac/manager.go
> fix: the ClusterRoleBindings capsule-namespace-provisioner are not reconciled when --capsule-user-group changes

- charts/capsule/templates/post-install-job.yaml
- charts/capsule/templates/pre-delete-job.yaml
> build(helm): using different names for Job hooks

- docs/operator/contributing.md
Fix #274 
Changed OperatorSDK version from v1.9 to v1.7.2.
> docs: Fixed typo

- docs/operator/contributing.md
Closes #277 
Golang version changed from `1.13.4` to `1.16` in **contributing** section.
> docs: Updated Golang version

- Dockerfile
> build: using Quay.io-hoested builder image

- controllers/tenant_controller.go
- main.go
- pkg/webhook/namespacequota/validating.go
- pkg/webhook/ownerreference/patching.go
- pkg/webhook/tenantprefix/validating.go
Closes #173.
The `reason` field is going to be the webhook involved in the action or the Namespace where the change or creation is happening.
Inspecting the events the `OperationResult` metadata can be extracted from the annotations.
```json
{
"metadata": {
"name": "oil.1685b95bcdc7d18f",
"namespace": "default",
"uid": "46b26789-72d3-41d1-a85d-284d1f90fa5b",
"resourceVersion": "18607",
"creationTimestamp": "2021-06-05T15:36:22Z",
"annotations": {
"OperationResult": "unchanged"
},
"managedFields": [
{
"manager": "manager",
"operation": "Update",
"apiVersion": "v1",
"time": "2021-06-05T15:36:22Z",
"fieldsType": "FieldsV1",
"fieldsV1": {"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{"f:apiVersion":{},"f:kind":{},"f:name":{},"f:resourceVersion":{},"f:uid":{}},"f:lastTimestamp":{},"f:me …
```
> Providing events to Tenant resources

- controllers/tenant_controller.go
- e2e/additional_role_bindings_test.go
> Avoiding Namespace's RoleBinding labels collision

- api/v1alpha1/domain/imagepullpolicy.go
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- config/manager/kustomization.yaml
- config/webhook/manifests.yaml
- config/webhook/patch_ns_selector.yaml
- docs/operator/use-cases/images-pullpolicy.md
- docs/operator/use-cases/network-policies.md
- docs/operator/use-cases/overview.md
- e2e/imagepullpolicy_multiple_test.go
- e2e/imagepullpolicy_single_test.go
- e2e/pod_priority_class_test.go
- main.go
- pkg/webhook/imagepullpolicy/errors.go
- pkg/webhook/imagepullpolicy/validating.go
> Image PullPolicy enforcement for v1alpha

- controllers/tenant_controller.go
- e2e/ingress_hostnames_test.go
- e2e/resource_quota_exceeded_test.go
- main.go
- pkg/webhook/handler.go
- pkg/webhook/imagepullpolicy/errors.go
- pkg/webhook/imagepullpolicy/validating.go
- pkg/webhook/ingress/validating.go
- pkg/webhook/namespacequota/validating.go
- pkg/webhook/networkpolicies/validating.go
- pkg/webhook/ownerreference/patching.go
- pkg/webhook/podpriority/validating.go
- pkg/webhook/pvc/validating.go
- pkg/webhook/registry/validating.go
- pkg/webhook/router.go
- pkg/webhook/services/errors.go
- pkg/webhook/services/validating.go
- pkg/webhook/tenant/validating.go
- pkg/webhook/tenantprefix/validating.go
- pkg/webhook/utils/in_capsule_groups.go
> feat: emitting events for policies violations

- controllers/tenant_controller.go
> Avoiding concurrent map write during Namespace metadata sync

- pkg/webhook/services/errors.go
- pkg/webhook/services/validating.go
> nil pointer dereference on IP parsing

- hack/create-user-openshift.sh
- hack/create-user.sh
> Exit from user creation flow when encountered error

- api/v1alpha1/tenant_func.go
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- config/webhook/manifests.yaml
- config/webhook/patch_ns_selector.yaml
- docs/operator/use-cases/cordoning-tenant.md
- docs/operator/use-cases/multiple-tenants.md
- docs/operator/use-cases/overview.md
- docs/operator/use-cases/pod-priority-class.md
- docs/operator/use-cases/resources-quota-limits.md
- e2e/tenant_cordoning_test.go
- main.go
- pkg/webhook/namespace/errors.go
- pkg/webhook/namespace/freezed.go
- pkg/webhook/namespace/quota.go
- pkg/webhook/namespacequota/validating.go
- pkg/webhook/tenant/cordoning.go
- pkg/webhook/tenant/validating.go
- pkg/webhook/utils/is_tenant_or_sa_request.go
> Tenant cordoning

- charts/capsule/README.md
- charts/capsule/templates/metrics-rbac.yaml
- charts/capsule/templates/servicemonitor.yaml
- charts/capsule/values.yaml
- config/grafana/dashboard.json
- config/prometheus/kustomization.yaml
- config/prometheus/monitor.yaml
- config/prometheus/role.yaml
- config/prometheus/rolebinding.yaml
> Created Grafana Dashboard and related charts/manifests

- docs/operator/managed-kubernetes/getting-started-amazon-eks.md
> Add Amazon EKS documentation

- charts/capsule/templates/configuration-default.yaml
- e2e/ingress_hostnames_allowed_collision_test.go
- e2e/tenant_ingress_hostnames_collision_allowed_test.go
> Inverted CapsuleConfiguration collision keys

- charts/capsule/README.md
- charts/capsule/templates/deployment.yaml
- charts/capsule/values.yaml
> Support for hostNetwork support on Helm chart

- controllers/tenant_controller.go
> fix: ensuring single reconciliation for Capsule RoleBinding resources

- e2e/tenant_ingress_hostnames_collision_allowed_test.go
- e2e/tenant_ingress_hostnames_collision_blocked_test.go
> test(e2e): avoiding flaky tests for ingress hostnames collision

- docs/operator/use-cases/overview.md
- docs/operator/use-cases/velero-backup-restoration.md
- hack/velero-restore.sh
Closes #312 
The script is done but I would make other tests on a real environment.
> velero restoration management script

- api/v1alpha1/zz_generated.deepcopy.go
- api/v1beta1/tenant_status.go
- api/v1beta1/tenant_types.go
- api/v1beta1/zz_generated.deepcopy.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- controllers/tenant_controller.go
> Tenant cordoning state

- controllers/secret/ca.go
> bug: ensuring to update the conversion webhook CA bundle

- api/v1alpha1/conversion_hub.go
> fix: avoid nil slice during resource conversion

- docs/operator/use-cases/velero-backup-restoration.md
- hack/velero-restore.sh
> velero-restore improvements

- docs/operator/use-cases/images-pullpolicy.md
- docs/operator/use-cases/network-policies.md
- docs/operator/use-cases/permissions.md
- docs/operator/use-cases/pod-security-policies.md
- docs/operator/use-cases/resources-quota-limits.md
These are a few minor improvements that I briefly put together while reading the docs. Please take a look and see if they're useful.
> docs: Minor improvements

- config/samples/capsule_v1beta1_tenant.yaml
- config/samples/kustomization.yaml
> Updating samples with v1beta1 sample manifest

- docs/proxy/standalone.md
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>
> doc: update capsule-proxy docs

- charts/capsule/README.md
> Added namespace creation

- api/v1alpha1/conversion_hub.go
- api/v1alpha1/conversion_hub_test.go
- api/v1beta1/resource_quota.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- config/install.yaml
- config/manager/kustomization.yaml
- controllers/tenant_controller.go
- e2e/tenant_resources_test.go
> Tenant or Namespace scope for resource quota budgets

- config/grafana/dashboard.json
Required for #301, just some improvements on getting more insights on Capsule.
@ptx96 I guess you can start using this for the docs, we can fine-tune this later but I guess it's a good starting point.
> feat: adding webhook and rest client latency per endpoint

- .github/workflows/docker-ci.yml
> Use build-args inside build-push action

- api/v1beta1/tenant_status.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- config/install.yaml
> Tenant status enums must be capitalized

- api/v1beta1/tenant_types.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- config/install.yaml
> Fix PriorityClasses description in CRD

- charts/capsule/templates/servicemonitor.yaml
- charts/capsule/values.yaml
> additional servicemonitor helm values support

- charts/capsule/README.md
- charts/capsule/templates/_helpers.tpl
- charts/capsule/templates/ca.yaml
- charts/capsule/templates/certs.yaml
- charts/capsule/templates/configuration-default.yaml
- charts/capsule/templates/deployment.yaml
- charts/capsule/templates/metrics-rbac.yaml
- charts/capsule/templates/metrics-service.yaml
- charts/capsule/templates/mutatingwebhookconfiguration.yaml
- charts/capsule/templates/podsecuritypolicy.yaml
- charts/capsule/templates/post-install-job.yaml
- charts/capsule/templates/pre-delete-job.yaml
- charts/capsule/templates/rbac.yaml
- charts/capsule/templates/serviceaccount.yaml
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- charts/capsule/templates/webhook-service.yaml
- charts/capsule/values.yaml
> build(helm): add customLabels and customAnnotations params

- .github/workflows/ci.yml
> ci(gh): adding git semantic commit message check

- charts/capsule/Chart.yaml
- charts/capsule/README.md
> build(helm): update chart and app version

- docs/operator/contributing.md
- docs/proxy/contributing.md
> Update the coding style guide in docs

- config/grafana/dashboard.json
> Change webhook metric used in Grafana dashboard

- main.go
- pkg/indexer/indexer.go
> fix: skipping indexer if error is a NoKindMatch

- docs/operator/use-cases/create-namespaces.md
- docs/operator/use-cases/images-pullpolicy.md
- docs/operator/use-cases/onboarding.md
- docs/operator/use-cases/resources-quota-limits.md
IMHO, this is the best set of docs regarding what considerations must be taken while thinking/designing multitenancy support in Kubernetes.
While walking the docs through one by one, I spotted some small issues and this is a small PR to fix all I found.
> fix doc minor issues

- charts/capsule/Chart.yaml
- charts/capsule/templates/mutatingwebhookconfiguration.yaml
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- charts/capsule/values.yaml
> build(helm): additional webhook configuration in chart

- .github/workflows/e2e.yml
- .github/workflows/helm.yml
- config/install.yaml
- config/manager/kustomization.yaml
Several changes are included to this PR
* allowing tag creation as trigger to push helm chart 
* including auto-generated
* limiting e2e tests to changes in specific paths
> Allowing tag creation as trigger to push helm chart

- charts/capsule/Chart.yaml
- charts/capsule/templates/validatingwebhookconfiguration.yaml
> fix(helm): remove matchExpressions selector from ingresses webhook

- e2e/suite_test.go
> Avoid CRD reinstall from e2e test suite

- api/v1alpha1/conversion_hub.go
- controllers/secret/ca.go
- controllers/secret/const.go
- controllers/secret/reconciler.go
- main.go
> fix: do not register tenant controller\webhook\indexer until CA is created

- charts/capsule/Chart.yaml
- charts/capsule/templates/post-install-job.yaml
- charts/capsule/templates/pre-delete-job.yaml
Add imagePullSecrets to post-install-jobs and pre-delete-jobs
Closes https://github.com/clastix/capsule/issues/486
> fix: add imagePullSecrets to jobs

- docs/content/general/mtb.md
- docs/gridsome.server.js
> docs: restoring multi-tenancy benchmark results

- README.md
> fix(docs): broken link for documentation static website

- controllers/servicelabels/abstract.go
> fix: ignore NotFound error in ServiceLabelsReconciler

- charts/capsule/crds/tenant-crd.yaml
> feat(helm): add default conversion webhook configuration to tenant CRD

- .github/workflows/e2e.yml
> chore(ci): e2e for kubernetes v1.23

- charts/capsule/Chart.yaml
- config/install.yaml
- config/manager/kustomization.yaml
> Releasing v0.1.1

- charts/capsule/Chart.yaml
- charts/capsule/templates/_helpers.tpl
> fix: Remove + from jobs.image.tag if found

- docs/content/general/tutorial.md
> Clarify usage of serviceaccount as tenant owner

- api/v1beta1/tenant_annotations.go
> fix: object count resource quotas not working when using Tenant scope

- e2e/forbidden_annotations_regex_test.go
- main.go
- pkg/webhook/tenant/forbidden_annotations_regex.go
Hiya!
I'm writing a PR for the issue #510 
I managed to write some code to fix the missing check
Please do not merge yet, as I still need to write the test
> fix: validate regex patterns in annotations #510

- docs/content/contributing/development.md
> fix(docs): adding missing validatingwebhookconfiguration patch for nodes endpoint

- docs/content/contributing/development.md
- docs/content/general/proxy.md
- e2e/forbidden_annotations_regex_test.go
- hack/velero-restore.sh
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> Misc typo fixes

- charts/capsule/README.md
- docs/content/general/tutorial.md
> Docs update

- charts/capsule/Chart.yaml
- charts/capsule/templates/ca.yaml
- charts/capsule/templates/certs.yaml
> fix(helm): avoiding overwriting secrets upon helm upgrade

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
> chore(ci): force use of go 1.16

- charts/capsule/Chart.yaml
- charts/capsule/templates/post-install-job.yaml
- charts/capsule/templates/pre-delete-job.yaml
> fix(helm): jobs in capsule helm chart should use the same tolerations as deployment

- controllers/secret/ca.go
Closes #546.
After `helm upgrade`, the CA bundle of dynamic admission controllers is aligned to the one managed by Capsule.
> fix: ensuring ca bundle replication upon helm upgrade

- api/v1alpha1/conversion_hub_test.go
- api/v1beta1/owner_role.go
- controllers/rbac/const.go
- controllers/tenant/manager.go
- controllers/tenant/rolebindings.go
- docs/content/general/mtb.md
- docs/content/general/tutorial.md
- e2e/additional_role_bindings_test.go
- e2e/dynamic_tenant_owner_clusterroles_test.go
- e2e/new_namespace_test.go
- e2e/node_user_metadata_test.go
- e2e/utils_test.go
Closes #524.
~Missing tests, any help on writing them would be superb.~
> Dynamic cluster roles for Tenant owners

- docs/content/general/proxy.md
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
> docs(general/proxy): remove duplicated doc about nodes

- README.md
> It closes #560
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
> docs(readme.md): add links to community repo and governance doc

- docs/content/general/proxy.md
This pull requests adds a use case for ProxySetting CRD - https://github.com/clastix/capsule/issues/531
Previously opened pull requests for ProxySetting CRD docs - https://github.com/clastix/capsule/pull/537
> docs: documenting proxysetting crd use cases in capsule-proxy

- api/v1beta1/custom_resource_quota.go
- pkg/webhook/tenant/custom_resource_quota.go
> fix: using sentinel error for non limited custom resource

- README.md
- docs/content/guides/charmed.md
- docs/gridsome.server.js
> docs: documenting charmed operator

- Makefile
- charts/capsule/README.md
- charts/capsule/values.yaml
- config/install.yaml
- config/manager/kustomization.yaml
- docs/content/contributing/development.md
> Switching over Docker Hub image

- docs/content/general/tutorial.md
Fixes: https://github.com/clastix/capsule/issues/573
> update tenant owner default clusterrole documentation

- README.md
- docs/content/index.md
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
> docs: fix typos

- controllers/rbac/const.go
- e2e/tenant_protected_webhook_test.go
Minor improvements regarding #586 and #587.
> Minor clean-ups

- charts/capsule/README.md
> helm example was wrong when customizing value

- api/v1beta1/owner_role.go
- controllers/tenant/rolebindings.go
- docs/content/general/tutorial.md
> Supporting dynamic tenant owner cluster roles although using non RFC 1123 compliant name

- charts/capsule/Chart.yaml
- charts/capsule/README.md
- charts/capsule/templates/_helpers.tpl
- charts/capsule/templates/daemonset.yaml
- charts/capsule/templates/pre-delete-job.yaml
- charts/capsule/values.yaml
- config/install.yaml
- config/manager/kustomization.yaml
> Add DaemonSet deploy option in Helm Chart

- charts/capsule/Chart.yaml
Closes #604.
Once merged, I'll tag a new helm tag to trigger the publishing of the chart.
> chore(helm): releasing new helm chart

- docs/content/general/proxy.md
> docs: documenting capsule-proxy metrics

- docs/content/general/tutorial.md
> Clarify tenant owner permissions in documentation

- docs/content/guides/velero.md
> document tenant backup and restore with velero

- .github/workflows/gosec.yml
> ci: add gosec pipeline

- ADOPTERS.md
@prometherion  Don't know if that looks good enough ;D
> feat: add bedag as adopters

- CODE_OF_CONDUCT.md
Adding a code of conduct for the Capsule project.
> chore: adding code of conduct

- controllers/servicelabels/abstract.go
> fix: service controller not skipping sentinel errs

- .github/workflows/e2e.yml
- controllers/servicelabels/endpoint_slices.go
- e2e/service_metadata_test.go
> Supporting Kubernetes 1.26

- e2e/namespace_user_metadata_test.go
- pkg/webhook/namespace/user_metadata.go
> fix: inverted logic in forbidden user namespace metadata

- Makefile
- api/v1beta2/tenant_types.go
- api/v1beta2/zz_generated.deepcopy.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- config/install.yaml
- docs/content/general/crds-apis.md
- docs/content/general/tutorial.md
- e2e/pod_runtime_class_test.go
- main.go
- pkg/webhook/pod/priorityclass_errors.go
- pkg/webhook/pod/runtimeclass.go
- pkg/webhook/pod/runtimeclass_errors.go
- pkg/webhook/utils/error.go
Signed-off-by: Oliver Baehler <oliver.baehler@hotmail.com>
This PR resolves multiple bugs/features:
- Implements #633 
- Corrects local Development commands in Makefile
- Validate on Image Pod Updates Registry according to tenant configuration
Currently under development, have to test everything tomorrow.
> feat: add runtimeclass control

- docs/content/general/tutorial.md
> fix(docs): limit range spec for pods and containers limits

- ADOPTERS.md
Add Wargaming to Capsule adopters
> add Wargaming to adopters

- controllers/pv/controller.go
- docs/content/general/tutorial.md
- e2e/preventing_pv_cross_tenant_mount_test.go
- main.go
- pkg/webhook/pvc/errors.go
- pkg/webhook/pvc/pv.go
- pkg/webhook/pvc/validating.go
> Preventing  PersistentVolume cross-Tenant mount

- controllers/resources/processor.go
> bug(tenantresources): using actual resourceversion during createorupdate

- api/v1beta2/tenant_conversion_hub.go
> fix: converting the status between v1beta1 and v1beta2

- charts/capsule/Chart.yaml
- config/install.yaml
- config/manager/kustomization.yaml
- docs/content/guides/upgrading.md
Bumping Helm Chart and preparing fo v0.2.1 relase.
> v0.2.1 release

- README.md
Just added CI status badge in README.md as per documentation best practices.
> Add CI status badge in readme.

- docs/content/general/proxy.md
> docs: latest changes in capsule proxy

- ADOPTERS.md
> Adding Fastweb as adopter

- pkg/webhook/namespace/owner_reference.go
- pkg/webhook/namespace/patch.go
Fixes https://github.com/clastix/capsule/issues/733
> fix: fixed namespace webhooks

- docs/content/guides/kubernetes-dashboard.md
Hi,
Update for the kubernetes dashboard guide
> Dashboard guide updates

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/gosec.yml
- .github/workflows/helm.yml
- pkg/webhook/defaults/handler.go
- pkg/webhook/defaults/ingress.go
- pkg/webhook/defaults/pods.go
- pkg/webhook/defaults/storage.go
- pkg/webhook/ingress/types.go
> fix: enforcing namespace for default mutators

- docs/content/guides/upgrading.md
> fix(docs): wrong manifests urls for migration

- ADOPTERS.md
Capsule used in an experimental Kubernetes cluster.
> Added POLITO among adopters

- ADOPTERS.md
> Update ADOPTERS.md - adding Reevo as Adopter

- controllers/tls/manager.go
> fix: missing v1beta2 version for CRD ConversionReviewVersions

- ADOPTERS.md
> Add PITS Global Data Recovery Services

- pkg/webhook/pvc/pv.go
> fix: incorrect capsule label comparison in PVC webhook

- Dockerfile
> deps(go): upgrading to 1.19.10

- docs/content/general/tutorial.md
> Update documentation regarding possible overwrite of the initial network policies set by tenant admin

- charts/capsule/Chart.yaml
- charts/capsule/README.md
- charts/capsule/templates/deployment.yaml
- charts/capsule/values.yaml
Fixes #799 
Add support for Capsule deployment `topologySpreadConstraints` in Capsule Helm Chart.
> feat(helm): add topologySpreadConstraints

- controllers/resources/global.go
- controllers/resources/processor.go
> fix(gosec): implicit memory aliasing in for loop

- e2e/ingress_hostnames_test.go
- pkg/webhook/ingress/errors.go
- pkg/webhook/ingress/validate_hostnames.go
> fix(ingress): always deny empty hostnames

- api/v1beta2/tenant_annotations.go
- controllers/tenant/resourcequotas.go
> fix: resource quota annotations key max length support

- docs/content/guides/rancher-projects/capsule-proxy-rancher.md
- docs/content/guides/rancher-projects/capsule-rancher.md
- docs/content/guides/rancher-projects/introduction.md
- docs/content/guides/rancher-projects/oidc-keycloak.md
- docs/gridsome.server.js
> Document how Capsule integrates with Rancher Projects

- .github/workflows/helm-publish.yml
> chore(github): using new secrets for GH pages Helm chart push

- .github/workflows/check-pr.yml
> chore(repo): remove wip feature

- docs/gridsome.config.js
- docs/package.json
- docs/yarn.lock
> chore(website): adding google analytics

- SELF_ASSESSMENT.md
> docs: security self assessment

- charts/capsule/Chart.yaml
> chore(helm): releasing v0.5.2

- api/v1beta2/tenant_annotations.go
- controllers/tenant/resourcequotas.go
> fix: sync quota values from tenant to resourcequota object

- controllers/tenant/resourcequotas_quota.go
> fix(quota-resources): skipping from count delete-marked objects

- api/v1beta2/tenant_annotations.go
> fix: ensuring resourcequota name doesn't break DNS-1123

- charts/capsule/Chart.yaml
> chore(helm): releasing v0.5.3

- controllers/tenant/namespaces.go
- controllers/tls/manager.go
- e2e/globaltenantresource_test.go
- e2e/tenantresource_test.go
> feat: ensuring well-known label

- Makefile
- controllers/resources/processor.go
- e2e/tenantresource_test.go
> fix(controller): respect metadata of replicated items

- docs/content/general/crds-apis.md
- docs/content/general/lens.md
- docs/template/reference-cr.tmpl
Fixes the problem described in https://github.com/projectcapsule/capsule/issues/933.
> docs(links): Fixed dead links

- .goreleaser.yml
- Makefile
> fix: correcting ldflags name

- .github/maintainers.yaml
> chore(.github/maintainers.yaml): add maxgio92 as new maintainer

- .github/workflows/e2e.yml
> test(e2e): bump used kubernetes versions

- GOVERNANCE.md
- MAINTAINERS.md
close #901 
based on [CNCF Governance Template](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md).
> chore: document project governance

- api/v1beta2/tenant_types.go
- charts/capsule/crds/tenant-crd.yaml
- config/crd/bases/capsule.clastix.io_tenants.yaml
- config/install.yaml
- docs/content/general/crds-apis.md
> fix(controller): add boolean defaults 

- .github/workflows/gosec.yml
> ci(gosec): fix sarif upload

- .github/workflows/releaser.yml
Should fix the releaser, currently failing
> chore: fix goreleaser

- ADOPTERS.md
@MaxFedotov @maxgio92 @oliverbaehler sharing this terrific news with the core maintainers! 🚀
> chore(adopters): department of defense is a capsule adopter

- charts/capsule/templates/crd-lifecycle/job.yaml
Remove duplicate `restartPolicy` in crd-lifecycle job for capsule helm chart.
> fix(helm): remove duplicate restartpolicy

- pkg/webhook/ownerreference/patching.go
Addressing the changes required from the linting rules
> chore(style): golangci-lint required changes

- .github/workflows/e2e.yml
- Makefile
- README.md
- SECURITY.md
- charts/capsule/Chart.yaml
- charts/capsule/README.md
- charts/capsule/README.md.gotmpl
- charts/capsule/templates/_helpers.tpl
- charts/capsule/templates/crd-lifecycle/_helpers.tpl
- charts/capsule/templates/crd-lifecycle/job.yaml
- charts/capsule/templates/mutatingwebhookconfiguration.yaml
- charts/capsule/templates/post-install/_helpers.tpl
- charts/capsule/templates/post-install/job.yaml
- charts/capsule/templates/pre-delete/job.yaml
- charts/capsule/values.yaml
- renovate.json
It do what it do:
- Aligns renovate, removing grouping of go dependencies, to simplify updates
- Fixes KIND and makes version handling in Makefile nicer
- Change Links
> chore: minor fixes in repository

- docs/content/general/tutorial.md
- pkg/webhook/pvc/errors.go
Just a quick adjustment of some typos.
> chore: update errors.go with spelling error fixes

- ADOPTERS.md
> chore(docs): add enreach to adopters

- Dockerfile.tracing
fix(ci): make harpoon binary executable
> fix(ci): make harpoon binary executable

- .github/workflows/e2e.yml
- e2e/utils_test.go
> fix(ci): switch to large runner for e2e tests

- .goreleaser.yml
Adds a WebAssembly build, to be ready for the future :D
> feat: add wasm release binary

- .goreleaser.yml
> fix(release): wasm build id

- .goreleaser.yml
Currently too many dependencies therefor not functional
> chore: remove wasm build

- .github/workflows/stale.yml
- .pre-commit-config.yaml
- charts/capsule/templates/crd-lifecycle/job.yaml
- charts/capsule/templates/post-install/job.yaml
- charts/capsule/templates/pre-delete/job.yaml
> chore: housekeeping tasks

- charts/capsule/Chart.lock
- charts/capsule/Chart.yaml
chore(deps): update capsule-proxy docker tag to v0.9.5
> chore(deps): update capsule-proxy docker tag to v0.9.5

- .github/workflows/docker-publish.yml
- .goreleaser.yml
> chore: fix binary directory

- .github/workflows/releaser.yml
chore(releaser): change size of the runner
> chore(releaser): change size of the runner

- charts/capsule/README.md
- charts/capsule/README.md.gotmpl
- charts/capsule/templates/mutatingwebhookconfiguration.yaml
- charts/capsule/templates/validatingwebhookconfiguration.yaml
- charts/capsule/values.schema.json
- charts/capsule/values.yaml
> feat(helm): improve admission configurations

- charts/capsule/templates/configuration-default.yaml
> fix(helm): change empty value handling

- pkg/meta/labels.go
migrates label from the capsule-proxy repository
> feat(api): migrate capsule.clastix.io/managed-by to meta api
