projectcapsule/capsule

Makefile
cmd/manager/main.go
pkg/cert/ca.go
pkg/cert/ca_test.go
pkg/cert/errors.go
pkg/controller/secret/errors.go
pkg/controller/secret/reconciler.go
pkg/controller/secret/secret_ca_controller.go
pkg/controller/secret/secret_tls_controller.go
pkg/controller/tenant/tenant_controller.go
pkg/webhook/owner_reference/patching.go

Closes #6.
The `GetCertificateAuthority` _Reconciler_ func was also creating a new CA without storing into Kubernetes, causing a race condition, getting a TLS generated from a CA that wasn't used by the mutating webhook configuration.

Avoiding TLS/CA race condition on Capsule installation

---

pkg/webhook/network_policies/validating.go

Closes #32.
Tenant owner was able to delete or update Capsule NetworkPolicy resources instead of their owns.

NetworkPolicy validating webhook logic was the opposite

---

controllers/namespace_controller.go
controllers/tenant_controller.go

Closes #27.
```
tenant.capsule.clastix.io/oil created
NAME   NAMESPACE QUOTA   NAMESPACE COUNT
oil    3                 0
```

Moving the Namespace count reconciliation to the Tenant reconciler

---

config/webhook/manifests.yaml
main.go
pkg/webhook/tenant_prefix/patching.go

Closes #34: just need to use the arg `--force-tenant-prefix` to setup the proper webhook.
```
INFO    setup   Operator Version: 0.0.1
INFO    setup   Go Version: go1.13.14
INFO    setup   Go OS/Arch: linux/amd64
INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
INFO    setup   Enabling the Namespace Tenant Prefix webhook
```
Once done, create a Tenant (`oil`, our sample Tenant) and issue a Namespace creation as Tenant owner:
```
namespace/oil-production created
```

Programmatic Tenant prefix for the Capsule namespaces

---

config/manager/manager.yaml
contributing.md
main.go

Closes #46.
All the pieces of information have been provided by the [following doc](https://sdk.operatorframework.io/docs/golang/references/logging).

Adding zap controlled by CLI flags

---

controllers/secret/ca.go
controllers/secret/tls.go
pkg/cert/ca.go

Closes #42: essentially, we're validating the certificate at each Capsule start-up, generating a new one in case of CA change for any reason.

Implementing Capsule certificate validation

---

README.md
e2e/custom_capsule_group_test.go
e2e/ingress_class_test.go
e2e/overquota_namespace_test.go
e2e/owner_webhooks_test.go
e2e/protected_namespace_regex_test.go
e2e/resource_quota_exceeded_test.go
e2e/selecting_tenant_test.go
e2e/storage_class_test.go
e2e/tenant_resources_changes_test.go
e2e/tenant_resources_test.go
e2e/utils_test.go
main.go
pkg/webhook/tenant_prefix/patching.go

This PR closes #72 and adds configuration parameter `protected-namespace-regex` which disallow users to create namespaces whose name matches this regexp.
It's completely backward-compatible, as default `protected-namespace-regex` is set to empty string.

Add protected-namespace-regex flag

---

config/manager/manager.yaml
controllers/secret/ca.go
controllers/secret/reconciler.go
controllers/secret/tls.go
main.go

Closes #77.
Just keep in mind that installation is a bit tricky since we're not relying only on Namespace but rather on several other components with the prefix `capsule`: tl;dr; the installation process via `make deploy` is not yet fully supported but I guess this is mandatory [for making this working properly](https://github.com/clastix/capsule-helm-chart/pull/2#issuecomment-686345914)

Making Namespace no more hard-coded

---

e2e/ingress_class_test.go
main.go
pkg/webhook/ingress/validating.go
pkg/webhook/pvc/validating.go

This PR is going to merge #105 and enhance the enforcement of Ingress resources, blocking any fraudulent creation performed by a _Service Account_ that wouldn't be matched by the `utils.InCapsuleGroup` utiliy.
e2e suite is green and tested on my own as following:
```
$: cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: web
spec:
serviceName: "nginx"
replicas: 2
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: k8s.gcr.io/nginx-slim:0.8
ports:
- containerPort: 80
name: web
volumeMounts:
- name: www
mountPath: /usr/share/nginx/html
volumeClaimTemplates:
- metadata:
name: www
spec:
storageClassName: forbidden  # since oil just allows the default one
accessModes: [ "ReadWriteOnce" ]
resources: …
```

Handling all the events from Storage and Ingress classes

---

pkg/webhook/service_labels/types.go

fix endpoint creation for services with selectors when servicesMetadata is specified for tenant

---

e2e/custom_capsule_group_test.go
e2e/force_tenant_prefix_test.go
e2e/ingress_class_test.go
e2e/namespace_metadata_test.go
e2e/new_namespace_test.go
e2e/overquota_namespace_test.go
e2e/owner_webhooks_test.go
e2e/protected_namespace_regex_test.go
e2e/resource_quota_exceeded_test.go
e2e/selecting_non_owned_tenant_test.go
e2e/selecting_tenant_fail_test.go
e2e/selecting_tenant_with_label_test.go
e2e/service_metadata_test.go
e2e/storage_class_test.go
e2e/tenant_name_webhook_test.go
e2e/tenant_owner_group_test.go
e2e/tenant_resources_changes_test.go
e2e/tenant_resources_test.go
pkg/webhook/owner_reference/patching.go
pkg/webhook/tenant/validating.go

This is an improvement started from the discussion on #113 and addressing also #106.
We would like to be less strict regarding Tenant naming, allowing end-users to use dashes according to [DNS RFC-1123](https://tools.ietf.org/html/rfc1123), the same applied by Kubernetes for some resources.
I'd like to get a review from @MaxFedotov since he was the author of the force tenant prefix.

Allowing dash on Tenant namespace

---

api/v1alpha1/tenant_types.go
config/crd/bases/capsule.clastix.io_tenants.yaml

Closes #137.
The output differs from the one requested on the issue due to the underlying library we're using:
```
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER NAME   OWNER KIND   NODE SELECTOR                  AGE
oil    3                 0                 alice        User         {"kubernetes.io/os":"linux"}   1s
```

Providing additional print column for the nodeSelector Tenant spec

---

main.go

Closes #139.
JSON output of logs:
```json
{"level":"info","ts":"2020-11-17T20:05:23.974+0100","logger":"setup","msg":"Capsule Version dev dirty"}
{"level":"info","ts":"2020-11-17T20:05:23.974+0100","logger":"setup","msg":"Build from: "}
{"level":"info","ts":"2020-11-17T20:05:23.974+0100","logger":"setup","msg":"Build date: "}
{"level":"info","ts":"2020-11-17T20:05:23.974+0100","logger":"setup","msg":"Go Version: go1.13.8"}
{"level":"info","ts":"2020-11-17T20:05:23.974+0100","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
```
We can switch to `RFC3339` or `RFC3339Nano` as well, but I guess ISO is a nice standard, don't you think so @MaxFedotov?

Logging timestamp to ISO 8601

---

api/v1alpha1/tenant_annotations.go
controllers/tenant_controller.go
e2e/container_registry_test.go
use_cases.md

Closes #151.
Namespace resources are expecting to have additional annotations, as `capsule.clastix.io/allowed-registries` and `capsule.clastix.io/allowed-registries-regexp`.

Annotating Tenant's Namespaces with allowed registries

---

api/v1alpha1/tenant_func.go
api/v1alpha1/tenant_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/capsule/crds/tenant-crd.yaml
config/crd/bases/capsule.clastix.io_tenants.yaml
controllers/tenant_controller.go
e2e/additional_role_bindings_test.go
e2e/container_registry_test.go
e2e/custom_capsule_group_test.go
e2e/force_tenant_prefix_test.go
e2e/ingress_class_test.go
e2e/namespace_metadata_test.go
e2e/new_namespace_test.go
e2e/overquota_namespace_test.go
e2e/owner_webhooks_test.go
e2e/protected_namespace_regex_test.go
e2e/resource_quota_exceeded_test.go
e2e/selecting_non_owned_tenant_test.go
e2e/selecting_tenant_fail_test.go
e2e/selecting_tenant_with_label_test.go
e2e/service_metadata_test.go
e2e/storage_class_test.go
e2e/tenant_name_webhook_test.go
e2e/tenant_owner_group_test.go
e2e/tenant_resources_changes_test.go
e2e/tenant_resources_test.go
e2e/utils_test.go
pkg/webhook/ingress/validating.go
pkg/webhook/pvc/validating.go
pkg/webhook/tenant/validating.go

Closes #145, letting only `.spec.owner` be required and making all the others optional.
As a side effect, the e2e cases needed to be refactored a little bit since we can avoid declaring empty values thanks to the struct tag `omitempty`.

Only owner Tenant specification key is mandatory

---

Makefile

This issue happened due to the release of a release candidate not tracked into the Helm chart.
Our e2e test suite is using the local Chart that is version pinned to the latest stable release and, due to `Never` pull image policy, the Capsule manager Pod wasn't able to create the CA and TLS certificate, timing out.

Debugging GitHub action

---

docs/operator/getting-started.md

Hi all,
I was looking for the documentation for Capsule and I have found an error on the following link. On GitHub, it gives a 404 page.
Hope it can be useful!

Wrong link in getting started documentation

---

Dockerfile
Makefile

Fixes #213 
Hi, this will fix the dirty flag on the builds, I have moved out the `git diff` from the Dockerfile because we do not copy all the things inside the container.

Fix dirty flag on Capsule builds

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/deployment.yaml
charts/capsule/values.yaml
docs/operator/references.md
e2e/ingress_hostnames_allowed_collision_test.go
e2e/ingress_hostnames_denied_collision_test.go
go.mod
main.go
pkg/indexer/add_ingress.go
pkg/indexer/ingress/hostname.go
pkg/webhook/ingress/errors.go
pkg/webhook/ingress/types.go
pkg/webhook/ingress/validating.go

Closes #215.
By default, allowing Ingress hostname collision since it's the actual behavior of Capsule: for 0.1.0 we can change this making it breaking backed by the minor release.

Ingress hostname collision

---

pkg/indexer/add_ingress.go
pkg/webhook/ingress/validating.go

Closes #223.
This is going to solve the flakiness we saw with older versions.

Avoiding to start indexers for ingresses.networking.k8s.io on k8s < 1.19

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/deployment.yaml
charts/capsule/values.yaml
docs/operator/references.md
e2e/tenant_ingress_hostnames_collision_allowed_test.go
e2e/tenant_ingress_hostnames_collision_blocked_test.go
main.go
pkg/webhook/tenant/validating.go

Closes #206.
Editing the original message due to some mess during PRs.
A new CLI flag (`--allow-tenant-ingress-hostnames-collision`) is added, defaulted to `false` to preserve backward compatibility: in case of toggling, Capsule will skip the Tenant validation that checks for hostnames collision in the key `Spec.ingressHostnames.allowed`.
I summon @bsctl: we need your super QA powers, here!

Allowing multiple Tenant resources to share same exact list of allowed hostnames

---

pkg/webhook/ingress/validating.go

Closes #225.
I was able to replicate the issue and solving it by testing with the step-by-step instructions provided in the issue.
```
cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: example
namespace: oil-production
spec:
rules:
- host: example.com
http:
paths:
- path: /testpath
backend:
serviceName: test
servicePort: 80                              
EOF                                                        
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.networking.k8s.io/example created
$ cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress …
```

Preventing Ingress hostname collision also for Namespaces of the same Tenant

---

pkg/utils/user_group.go
pkg/utils/user_group_test.go
pkg/webhook/utils/in_capsule_group.go

Closes #234, as well for PR #235.
This change is going to be breaking for `capsule-proxy` or any other component relying on the binary-search for the Capsule group belonging: nothing critical, it's a matter of renaming since we're performing a _search_.
With this change, we're letting Capsule to run with the Capsule group set to `system:authenticated` (although, I wouldn't suggest this) and skipping the requests performed by controller managers running in the `kube-system` Namespace.
Tested with the following steps:
1. create the KinD local dev env
2. installing Capsule with CLI flag `--capsule-user-group=system:authenticated`
3. create a Tenant
4. create the Namespace (`--as alice --as-group system:authenticated`)
5. wait for the reconciliation in order to get `NetworkPolicy` resources …

Ignoring requests from kube-system ServiceAccount resources

---

.gitignore
hack/create-user.sh

This is a non-production code change, it's just required to setup Capsule while testing it, during CI or e2e of other components relying on it.

chore: non embedding certs for kubeconfig file generation

---

main.go
pkg/webhook/ingress/validating.go
pkg/webhook/namespacequota/validating.go
pkg/webhook/ownerreference/patching.go
pkg/webhook/pvc/validating.go
pkg/webhook/registry/validating.go
pkg/webhook/router.go
pkg/webhook/services/validating.go
pkg/webhook/tenant/validating.go
pkg/webhook/tenantprefix/validating.go
pkg/webhook/utils/in_capsule_group.go
pkg/webhook/utils/kubernetes_version.go

This is a WP PR to solve #164 
I plan to check the codebase file by file to improve variables names.
This is my approach to choose if a variable should be renamed:
I'm trying to understand the variable meaning by reading the code, if I need to search in the code base for that meaning, then I rename the variable.
Started with
@prometherion let me know if you like it and if you think I should continue.

refactor: better name variables in codebase

---

README.md

Fix typo in README: “Kuberentes”

---

api/v1alpha1/domain/podpriority.go
charts/capsule/templates/validatingwebhookconfiguration.yaml
config/webhook/manifests.yaml
config/webhook/patch_ns_selector.yaml
docs/index.md
docs/operator/use-cases/node-ports.md
docs/operator/use-cases/overview.md
docs/operator/use-cases/pod-priority-class.md
e2e/pod_priority_class_test.go
main.go
pkg/webhook/podpriority/errors.go
pkg/webhook/podpriority/validating.go

Partially addressing #257.
We have to plan a new version to handle this feature.

Pod Priority Class support

---

.github/workflows/docker-ci.yml
Dockerfile
charts/capsule/values.yaml

Closes #244
- Added armv7 / arm64 support (k8s deprecated armv6)
- Automated docker buildx & push to clastix quay.io registry using github actions
- Added proprietary kubectl image from quay.io
Completely tested on amd64 / arm64

Docker-ci for armv7 / arm64 support 

---

api/v1alpha1/conversion_hub.go
api/v1alpha1/conversion_hub_test.go
api/v1alpha1/tenant_webhook.go
api/v1alpha1/zz_generated.deepcopy.go
api/v1beta1/zz_generated.deepcopy.go
pkg/webhook/pod/imagepullpolicy_pullpolicy.go

v1beta1 conversion webhook

---

Makefile
config/crd/kustomizeconfig.yaml
config/manager/kustomization.yaml

Closes #321.
JFI @bsctl @MaxFedotov you have to ensure to download the latest `kustomize` when developing, otherwise you could create untracked files.

Updating kustomize

---

.github/workflows/ci.yml
Makefile
README.md
config/install.yaml
config/manager/kustomization.yaml

Closes #347.
Pretty sure you're happy for this, @bsctl.

Single YAML file installer

---

api/v1beta1/owner.go
api/v1beta1/tenant_status.go
api/v1beta1/tenant_types.go
charts/capsule/crds/tenant-crd.yaml
config/crd/bases/capsule.clastix.io_tenants.yaml
config/install.yaml

close #322 
```
$ kubectl explain tnt.spec
KIND:     Tenant
VERSION:  capsule.clastix.io/v1beta1
RESOURCE: spec <Object>
DESCRIPTION:
TenantSpec defines the desired state of Tenant
FIELDS:
additionalRoleBindings       <[]Object>
Specifies additional RoleBindings assigned to the Tenant. Capsule will
ensure that all namespaces in the Tenant always contain the RoleBinding for
the given ClusterRole. Optional.
containerRegistries  <Object>
Specifies the trusted Image Registries assigned to the Tenant. Capsule
assures that all Pods resources created in the Tenant can use only one of
the allowed trusted registries. Optional.
enableNodePorts      <boolean>
Specifies if NodePort service type resources are allowed for the Tenant.
Dafault is true. Optional.
externalServiceIPs   <Object>
Specifies …
```

feat: add description fields in crd

---

api/v1alpha1/conversion_hub.go
api/v1alpha1/conversion_hub_test.go
api/v1beta1/owner.go
charts/capsule/crds/tenant-crd.yaml
config/crd/bases/capsule.clastix.io_tenants.yaml
config/install.yaml

Closes #257, finally.
@MaxFedotov may I ask you if it's ok since you take care of the proxy actions?

Pod PriorityClass proxy operation support

---

.github/workflows/e2e.yml
controllers/secret/ca.go
controllers/tenant_controller.go

Partially addressing #148 since we're getting a huge performance boost on the expected reconciliation time since we're going to use several goroutines per resource Kind reconciliation (LimitRange, NetworkPolicy, ResourceQuota, etc) and per Namespace.
This will increase the amount of spawned goroutines with subsequent pressure on the memory side: from my actual test, I saw consumption of 1Gi of RAM reconciling a single Tenant collecting 200 Namespaces, not so bad since it's an edge case.
But the most important thing is that we're moving towards to address #49 too: we were doing something really stupid, triggering an update of the outer Resource Quotas per each Namespace, causing several 409 status codes and enqueuing back the Tenant several times. This was leaving enough time frame to …

refactor: using goroutines per Namespace for each resource Kind reconciliation

---

controllers/config/manager.go
main.go

fix: capsuleconfiguration controller package name should be config instead of rbac

---

docs/operator/mtb/allow-self-service-management-of-network-policies.md
docs/operator/mtb/allow-self-service-management-of-rolebindings.md
docs/operator/mtb/allow-self-service-management-of-roles.md
docs/operator/mtb/block-access-to-cluster-resources.md
docs/operator/mtb/block-access-to-multitenant-resources.md
docs/operator/mtb/block-access-to-other-tenant-resources.md
docs/operator/mtb/block-add-capabilities.md
docs/operator/mtb/block-modification-of-resource-quotas.md
docs/operator/mtb/block-network-access-across-tenant-namespaces.md
docs/operator/mtb/block-privilege-escalation.md
docs/operator/mtb/block-privileged-containers.md
docs/operator/mtb/block-use-of-existing-persistent-volumes.md
docs/operator/mtb/block-use-of-host-ipc.md
docs/operator/mtb/block-use-of-host-networking-and-ports.md
docs/operator/mtb/block-use-of-host-path-volumes.md
docs/operator/mtb/block-use-of-host-pid.md
docs/operator/mtb/block-use-of-nodeport-services.md
docs/operator/mtb/configure-namespace-object-limits.md
docs/operator/mtb/configure-namespace-resource-quotas.md
docs/operator/mtb/require-always-imagepullpolicy.md
docs/operator/mtb/require-persistentvolumeclaim-for-storage.md
docs/operator/mtb/require-reclaim-policy-of-delete.md
docs/operator/mtb/require-run-as-non-root-user.md
docs/operator/mtb/sig-multitenancy-bench.md
docs/operator/overview.md

Add sig-multitenancy-bench conformance

---

config/install.yaml
config/manager/kustomization.yaml
hack/create-user-openshift.sh
hack/create-user.sh

Update of `CertificateSigningRequest` API from `v1beta1` to `v1` requires the `spec.signerName` field to be specified.
Close #385

Add signerName in CSR hack script

---

docs/proxy/overview.md

Porting changes from clastix/capsule-proxy#132.

docs: updating capsule-proxy

---

Makefile
controllers/secret/tls.go

Closes #410.
Feedback about the issue and proposed solution would be great, @MaxFedotov @bsctl.

fix: deleting Pods upon TLS update for HA installations

---

main.go
pkg/webhook/tenant/serviceaccount_format.go

Closes #412.
Tested as follows:
```
cat <<EOF | kubectl apply -f -
pipe heredoc> apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
name: bug-tenant
spec:
owners:
- kind: ServiceAccount
name: some-service-account
EOF
Error from server (owner name some-service-account is not a valid Service Account name ): error when creating "STDIN": admission webhook "tenants.capsule.clastix.io" denied the request: owner name some-service-account is not a valid Service Account name
```
```
cat <<EOF | kubectl apply -f -
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
name: group-sa
spec:
owners:
- kind: ServiceAccount
name: system:serviceaccount:default
EOF
tenant.capsule.clastix.io/group-sa created
```
```
cat <<EOF | kubectl apply -f -
apiVersion: capsule.clastix.io/v1beta1 …
```

fix: validating Tenant owner name when is a ServiceAccount

---

hack/create-user.sh

This PR will try to fix the issue described over [here](https://github.com/clastix/capsule/issues/418).
It will add the `jq` installation checking to the `hack/create_user.sh` script

jq installation checking

---

api/v1beta1/deny_wildcard.go
e2e/disable_ingress_wildcard_test.go
e2e/ingress_class_extensions_test.go
e2e/ingress_class_networking_test.go
e2e/ingress_hostnames_collision_cluster_scope_test.go
e2e/ingress_hostnames_collision_disabled_test.go
e2e/ingress_hostnames_collision_namespace_scope_test.go
e2e/ingress_hostnames_collision_tenant_scope_test.go
e2e/ingress_hostnames_test.go
e2e/service_metadata_test.go
main.go
pkg/webhook/ingress/validate_wildcard.go

Make programmable deny of wildcard hostnames

---

.github/workflows/helm.yml

Allowing tag creation as trigger to push helm chart

fix(ci): allowing tag creation as trigger to push helm chart

---

docs/operator/use-cases/deny-wildcard-hostnames.md
docs/operator/use-cases/namespace-labels-and-annotations.md
docs/operator/use-cases/overview.md
docs/operator/use-cases/velero-backup-restoration.md

add documentation about deny-wildcard annotation

---

.github/workflows/helm.yml

this commit remote helm release workflow trigger on create which triggers duplicate event as push
fixes: #459

release(fix) : duplicate release for helm chart

---

config/install.yaml
config/webhook/patch_ns_selector.yaml

fix: yaml installer should use namespace selector for pods webhook

---

controllers/secret/ca.go
controllers/secret/const.go
controllers/secret/tls.go
main.go

Closes #440.
This is going to solve the issue when upgrading Capsule <v0.1.0 to >=v0.1.0: due to a resource reflector many warnings were polluting the reconciliation loop and causing unmarshaling errors.
Additionally, just the CA secret was checked before starting the Operator, when also the TLS is requested for the webhooks, along with the `/convert` one that is used for the CR version conversion.

fix: starting all controller only when certificates are generated

---

charts/capsule/templates/_helpers.tpl
charts/capsule/values.yaml

Closes #462
if applied, this commit removes the static kubectl client tag and will use a dynamic tag based on the cluster version.
- it'll use the last tag of the matching "minor"
- it is always possible to override the value
this PR remains temporarily in draft, waiting for changes to the push logic of clastix/kubectl repository

feat(helm): find kubectl tag from server version

---

api/v1beta1/custom_resource_quota.go
controllers/tenant/manager.go
controllers/tenant/resourcequotas_quota.go
docs/content/general/tutorial.md
e2e/custom_resource_quota_test.go
main.go
pkg/webhook/tenant/custom_resource_quota.go
pkg/webhook/tenant/custom_resource_quota_errors.go

Closes #365.
```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
name: oil
annotations:
quota.resources.capsule.clastix.io/mysqls.databases.acme.corp_v1: "3"
spec:
owners:
- name: alice
kind: User
```
With this special annotation in the Tenant manifest, a Cluster Administrator can limit the amount of resources `MySQL` in the API Group `databases.acme.corp/v1` in all the Namespaces belonging to the Tenant.
> Obviously, Alice must have granted permissions to manage these Custom Resources using `additionalRoleBindings` Tenant specification key, and this feature can work only for Namespaced-scope resources.

Limiting the amount of Custom Resource instances deployed in a Tenant

---

docs/content/general/tutorial.md
docs/content/guides/upgrading.md
docs/gridsome.server.js

Documenting migration of Tenant custom resources from v1alpha1 to v1beta1

---

api/v1beta1/tenant_types.go
config/crd/bases/capsule.clastix.io_tenants.yaml
config/install.yaml
docs/content/general/references.md

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
Provides the right description for the `limitRanges` in TenantSpec, in turn applying that to the generated CRDs and updating the reference document.

chore(description): description for limitRanges and update doc

---

docs/content/general/proxy.md

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
Fixes the correct URL to `capsule-proxy` helm chart on the [Capsule Proxy](https://capsule.clastix.io/docs/general/proxy) page.

fix(docs): capsule-proxy chart url

---

Makefile

I tried to run `make manager` to make sure I can build capsure locally.
-> First attempt
```
make: *** No rule to make target `fmt', needed by `manager'.  Stop.
```
fmt and vet rules were missing. I added fmt and vet rules(as part of this commit)
-> Second attempt
```
go fmt ./...
go vet ./...
go build -o bin/manager main.go
./main.go:65:55: undefined: GitTag
./main.go:65:63: undefined: GitCommit
./main.go:65:74: undefined: GitDirty
./main.go:66:46: undefined: GitRepo
./main.go:67:46: undefined: BuildTime
make: *** [manager] Error 2
```
This is due to  passing main.go to build, while the package has multiple files
`main.go` and `version.go`, the missing symbols are in `version.go`
I fixed this by building root package. And now go is happy!
-> Third attempt
```
go fmt ./...
go vet ./...
go …
```

fix Makefile for building local binary with make manager

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/_helpers.tpl
charts/capsule/templates/ca.yaml
charts/capsule/templates/certificate.yaml
charts/capsule/templates/deployment.yaml
charts/capsule/templates/mutatingwebhookconfiguration.yaml
charts/capsule/templates/pre-delete-job.yaml
charts/capsule/templates/validatingwebhookconfiguration.yaml
charts/capsule/values.yaml
main.go

closes #554 
Added new flag to Capsule `enable-secret-controller`, which enables or disables secretcontroller reconcilers.
added 2 new options to Capsule helm chart:
- `manager.options.enableSecretController` - configures `enable-secret-controller` flag
- `certManager.generateCertificates` - enables cert-manager certificates yaml and other stuff

support cert-manager for generating tls and ca

---

controllers/tls/errors.go
controllers/tls/manager.go

Closes #594.
With the use of the sentinel error, I can skip the labeling of pods required by the latest changes introduced with #555.
```
2022-06-19T14:31:53.596+0200    INFO    controllers.TLS skipping annotation of Pods for cert-manager    {"Request.Namespace": "capsule-system", "Request.Name": "capsule-tls", "error": "cannot retrieve the leader Pod, probably running in out of the cluster mode"}
```

refactor: sentinel error for running in out of cluster mode

---

api/v1alpha1/capsuleconfiguration_annotations.go
charts/capsule/Makefile
charts/capsule/README.md
charts/capsule/README.md.gotmpl
charts/capsule/templates/NOTES.txt
charts/capsule/templates/_helpers.tpl
charts/capsule/templates/certs.yaml
charts/capsule/templates/configuration-default.yaml
charts/capsule/templates/mutatingwebhookconfiguration.yaml
charts/capsule/templates/post-install-job.yaml
charts/capsule/templates/pre-delete-job.yaml
charts/capsule/templates/validatingwebhookconfiguration.yaml
charts/capsule/values.yaml
controllers/tls/manager.go
main.go
pkg/configuration/client.go
pkg/configuration/configuration.go

This PR allows deeper integration with `cert-manager` by adding new Helm values.
- `certManager.generateCertificates`: allows to create the Certificate and Issuer requested by `cert-manager`, along with the required annotations for injecting the CA in the Mutating and Validating webhooks
- `tls.create`: allows to skip the creation of the secret, useful if it must be provided externally
- `tls.enableController`: allows to skip the start of the TLS reconciler, useful when `cert-manager` is injecting on its own the CA, or managed by a third party (e.g. Vault, or custom strategies)
Along with that, the `CapsuleConfiguration` has dropped the annotation `capsule.clastix.io/generate-certificates` in favor of `capsule.clastix.io/enable-tls-configuration` that allows controlling the start of the …

Integration with cert-manager

---

docs/content/guides/flux2-capsule.md

This PR updates the documentation about the integration with Flux.
In detail, the `ClusterRole` with privilege to patch `Namespace` besides create is no longer needed as it's bound now by Capsule by default, to tenant owners.

Update documentation on integration with Flux v2

---

docs/content/general/tutorial.md

after some discussion on slack with @prometherion here is my attempt to make the docs more clear.
> we don't know how's the platform admin is managing these ServiceAccount
We saw from other end-users that their best practice is to create a Namespace containing all the ServiceAccount resources that will be used as Tenant Owner (e.g: tenant-system) in order to user its group in the Capsule Configuration (e.g.: system:serviceaccounts:tenant-system).

docs: clarify serviceAccounts as tenant owner

---

.gitignore
Makefile
docs/content/contributing/development.md

Fixes some stuff I have experienced while developing locally:
- Correct GinkGO Path
- Exclude capsule bin with gitignore
- Split E2E Testing Recipes into three stages. e2e/* now always deletes the kind cluster. e2e-exec runs jsut ginkgo without rebuilding the cluster
- Correct Admission Webhooks Patches (Mutating path was incorrect, Validating had wrong order)
- Add documentation to fetch tags

feat: improve local development experience

---

.github/maintainers.yaml

With the following PR, I'm proposing @oliverbaehler step in as maintainer to the current project.
In the last months, Oliver showed proactivity in triaging the issues of Capsule, proposing enhancements, and fixing issues. Furthermore, Oliver is maintaining a Capsule installation at his current company, offering the community experience with a real and production use-case.

chore(maintainers): welcome oliver

---

api/v1beta2/ingress_options.go
api/v1beta2/namespace_options.go
charts/capsule/crds/tenant-crd.yaml
config/crd/bases/capsule.clastix.io_tenants.yaml
config/install.yaml
docs/content/contributing/development.md
docs/content/general/crds-apis.md
docs/content/general/getting-started.md
docs/content/general/mtb.md
docs/content/general/proxy.md
docs/content/general/tutorial.md
docs/content/guides/flux2-capsule.md
docs/content/guides/pod-security.md
docs/content/guides/upgrading.md
docs/gridsome.server.js

Closes #652.
Some API changes were requested due to missing `,omitempty` values that were preventing a smooth usage of Capsule.
All the Tenant manifests have been tested one by one, this leads me to the `,omitempty` issue.

Aligning documentation to v1beta2

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/daemonset.yaml
charts/capsule/templates/deployment.yaml
charts/capsule/values.yaml

Signed-off-by: Zemtsov Vladimir <zemtsov.v@mail366.com>
Small feature for control securityContext in helm
Local test:
```bash
~ kind create cluster
...
~ k cluster-info
Kubernetes control plane is running at https://127.0.0.1:60977
CoreDNS is running at https://127.0.0.1:60977/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
~ helm install capsule . -n capsule-system --create-namespace
NAME: capsule
LAST DEPLOYED: Fri Feb 10 09:57:02 2023
NAMESPACE: capsule-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
...
~ k get deployments.apps -n capsule-system capsule-controller-manager -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
...
name: capsule-controller-manager
namespace: …
```

refactor(helm): add control for securityContext

---

charts/capsule/Chart.yaml
charts/capsule/templates/post-install-job.yaml
charts/capsule/templates/pre-delete-job.yaml

local test:
```bash
~ kind create cluster
...
~ k cluster-info
Kubernetes control plane is running at https://127.0.0.1:61015
CoreDNS is running at https://127.0.0.1:61015/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
~ helm install capsule . -n capsule-system --create-namespace 
NAME: capsule
LAST DEPLOYED: Tue Feb 14 17:34:56 2023
NAMESPACE: capsule-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
...
~ k create -f - << EOF
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
name: oil
spec:
owners:
- name: alice
kind: User
EOF
tenant.capsule.clastix.io/oil created
~ k get tenants
NAME   STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
oil    Active …
```

feat(helm): add securityContexts to jobs

---

hack/local-test-with-kind.sh

Hi.
In the future, I will actively use capsule in my K8s clusters. For local test before PR in [this](https://github.com/clastix/capsule/pull/704) and [this](https://github.com/clastix/capsule/pull/701) PR I use kind.
I think this script will speed up local testing in the future

feat: add bash script for local-test capsule

---

controllers/resources/processor.go
e2e/tenantresource_test.go
go.mod
go.sum

Closes #688.
Supported keywords:
- `{{ tenant.name }}` for the Tenant name managing the Namespace
- `{{ namespace }}` for the Namespace where the resource is replicated
Still missing documentation for this feature.

Template support for resources replication

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/values.yaml

In templates daemonset.yaml/deployment.yaml/post-install-job.yaml/pre-delete-job.yaml used `.Values.imagePullSecrets`, not `.Values.manager.imagePullSecrets `

fix(helm): move imagePullSecrets to root values

---

go.mod
go.sum

chore(go): bumping up github.com/emicklei/go-restful to v2.16.0

---

charts/capsule/Chart.yaml

The latest tag in capsule is `0.2.2` but the appVersion in the chart.yaml is still pointing to the previous release i.e. `0.2.1` so incremented the appVersion.

chore(helm): bump up the appVersion

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/daemonset.yaml
charts/capsule/templates/deployment.yaml
charts/capsule/templates/webhook-service.yaml
charts/capsule/values.yaml
main.go

Fixes #715
In some networking contexts, operators may need to use a custom webhook port. This PR add the `webhook-port` CLI parameter, sets its default value to `9443` and passes it down to the manager. It also adds the `manager.webhookPort` Helm value to the chart and bindings to the service, deployment and daemonset resources.

feat: allow customization of the webhook port

---

api/v1beta2/owner.go
charts/capsule/crds/tenant-crd.yaml
config/crd/bases/capsule.clastix.io_tenants.yaml
config/install.yaml
docs/content/general/crds-apis.md

As discussed on #702, adding the missing required CRDs field for the Capsule Proxy integration.
Closes #706.

Capsule Proxy fixes

---

.github/workflows/ci.yml
.github/workflows/e2e.yml
Dockerfile
docs/content/contributing/development.md
go.mod

update capsule to golang 1.19 to allow for easier recompile using boringcrypto which was added to main in golang 1.19

fix: update golang to 1.19

---

controllers/resources/processor.go

fix: remove ownerReferences from tenantResource namespacedItems before applying them

---

docs/content/general/tutorial.md

Fixes: https://github.com/clastix/capsule/issues/794

docs: update docs to use forceTenantPrefix

---

README.md
docs/content/contributing/governance.md
docs/content/contributing/release.md
docs/content/dictionary.txt
docs/gridsome.server.js

Documenting Capsule release process

---

.github/workflows/fossa.yml

chore(ci): added fossa license check

---

CODE_OF_CONDUCT.md
README.md

This PR updates code of conducts by following the guidelines provided by the [CNCF code of conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md).

Update CoC by following CNCF CoC

---

.github/workflows/helm-publish.yml
README.md
charts/capsule/Chart.yaml

This bumps the used controller image to 0.4.0-rc.1. In addition, when we release a helm chart (eg. helm-v1.0.0) the version is extracted from the tag (in the case 1.0.0) and then used to publish the chart. So the version in the Chart.yaml does no longer require bumping for new releases.

feat(helm): bump controller version and simplify release flow

---

.github/workflows/releaser.yml
CONTRIBUTING.md
ROADMAP.md
SECURITY.md

Should solve the problem with goreleaser

chore(docs): add roadmap and retest goreleaser

---

README.md

The CLO Monitor checks for an SBOM reference in the README.md, therefor adding it.

docs(repo): add sbom reference

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/check-pr.yml
.github/workflows/helm-test.yml
.goreleaser.yml
CHANGELOG.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
charts/capsule/Chart.yaml
commitlint.config.js

Adds a lot of documentation, references changelog to where it's created. Ensures commits are formatted to or changelog's standards. The biggest dicussion point here, is regarding the types of changes and their scope which we accept. Most of the other changes are based on the ruleset. 
Let me know what you think: 
https://github.com/buttahtoast/capsule-cncf-slam/blob/feat/doc-changelog/CONTRIBUTING.md#semantics

feat: improve changelog documentation and linting

---

.github/workflows/check-pr.yml
SECURITY-INSIGHTS.yml
SECURITY.md

chore(repo): security insights

---

.github/dependabot.yml
.github/workflows/check-pr.yml
CONTRIBUTING.md
SECURITY-INSIGHTS.yml
commitlint.config.js

Mainly removes the requirement to create scoped, because its annoying.. :D

chore(repo): remove scopes as mandatory

---

.github/workflows/helm-test.yml
.ko.yaml
Makefile
charts/capsule/Chart.yaml

This prepares a new controller and chart release.
Changes the Chart-Testing flow, so it also builds the controller image

chore(chart): bump release

---

SECURITY-INSIGHTS.yml

According to the [CLOMonitor documentation](https://clomonitor.io/docs/topics/checks/#self-assessment):
> The details of the security self-assessment (including the evidence url) are available in the security-artifacts > self-assessment section of the [OpenSSF Security Insights](https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md) manifest file (SECURITY-INSIGHTS.yml) that should be located at the root of the repository.

chore(security-insights): self-assessment evidence

---

charts/capsule/Chart.yaml

chore(helm): prepare helm release

---

pkg/webhook/namespace/quota.go

Closes #868.
I tested the behaviour, and it's nice:
```
$: kubectl get tnt solar
NAME    STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
solar   Active   1                 1                                 27m
$: kubectl --as alice --as-group capsule.clastix.io create ns solar-test
namespace/solar-test created
$: kubectl --as alice --as-group capsule.clastix.io create ns solar-test
Error from server (AlreadyExists): namespaces "solar-test" already exists
$: kubectl --as alice --as-group capsule.clastix.io create ns solar-overquota
Error from server (Forbidden): admission webhook "namespaces.capsule.clastix.io" denied the request: Cannot exceed Namespace quota: please, reach out to the system administrators
```

feat(ux): namespace oncrete hook to check namespace exsistence

---

api/v1beta2/owner.go
controllers/tenant/manager.go
controllers/tenant/metadata.go
e2e/tenant_metadata.go
main.go
pkg/api/metadata_const.go
pkg/webhook/tenant/metadata.go

Initial efforts for the implementation of:
https://github.com/projectcapsule/capsule-proxy/issues/328

feat(tenant): add label with tenant name for each tenant

---

go.mod
go.sum
main.go

If the GOMAXPROCS environment variable is not explicitly set when starting the Go process, it defaults to the output of the runtime.NumCPU() function, which represents the number of available CPU cores (i.e., the value of P). 
**Verify** 
To verify if that's true, i added the following to main.go:
```
func MaxParallelism() int {
maxProcs := goRuntime.GOMAXPROCS(0)
numCPU := goRuntime.NumCPU()
if maxProcs < numCPU {
return maxProcs
}
return numCPU
}
//nolint:maintidx
func main() {
fmt.Println("MaxParallelism: ", MaxParallelism())
```
This print out how many cores will be allocated.
1. Deployed with the main build
```
kubectl logs -f capsule-controller-manager-8c89798fc-hv5gp -n capsule-system
MaxParallelism:  4
...
```
2. Deployed with the `go.uber.org/automaxprocs` import:
```
2023/11/30 …
```

fix(controller): respect group quotas for number of operating system threads allocated to goroutines

---

charts/capsule/README.md
charts/capsule/ci/test-values.yaml
charts/capsule/templates/rbac.yaml
charts/capsule/values.yaml

I haven't found anything where we use these ClusterRoles. In addition allows users to reference their own clusterRoles or Roles (resolves #771)

feat(chart): allow custom role bindings

---

config/grafana/dashboard.json

In grafana dashboard, prometheus datasource is hardcoded. This does fit every installation.
This PR make prometheus datasource a templating variable.

chore(grafana): configurable datastore

---

controllers/tenant/limitranges.go
controllers/tenant/networkpolicies.go
controllers/tenant/resourcequotas.go
controllers/tenant/rolebindings.go

fix: preserving externally managed labels

---

.github/workflows/helm-publish.yml
.goreleaser.yml

Causes everything to be released in the same version on tag

ci(release): use same tag for helm release

---

.github/configs/ct.yaml
.github/workflows/e2e.yml
.github/workflows/helm-test.yml
Makefile
charts/capsule/Chart.lock
charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/ci/proxy-values.yaml
charts/capsule/ci/test-values.yaml
charts/capsule/values.yaml

Adds Capsule-Proxy as subchart. Another notable changes is, that resources are unset by default. This is the standard for any helm chart. All the other changes help to make the chart-testing work.

feat(chart): add capsule-proxy 0.6.0 as optional dependency 

---

e2e/namespace_additional_metadata_test.go
pkg/webhook/namespace/freezed.go
pkg/webhook/namespace/prefix.go
pkg/webhook/namespace/quota.go
pkg/webhook/namespace/user_metadata.go
pkg/webhook/namespace/utils.go

While automating capsule for a HCI solution i noticed we have this bug. If you try to add another ownerreference you are always met with this error:
```
error: namespaces "cluster-fx9kggjwjd" could not be patched: admission webhook "namespaces.capsule.clastix.io" denied the request: Tenant.capsule.clastix.io "fx9kggjwjd" not found
```
`fx9kggjwjd` is representative for the new ownerreference name added. This fix checks if the ownerreference is actually from a tenant, if not it's skipped.

fix(controller): ensure iteration on capsule ownerreferences

---

controllers/tenant/resourcequotas.go

fix(resourcequotas): Update namespace-specific hard quota calculation logic

---

controllers/tenant/manager.go
controllers/tenant/resourcequotas.go
pkg/metrics/metrics.go

This PR adds two custom metrics for capsule tenants: 
- `capsule_tenant_resource_limit{resource="<resource>",resourcequotaindex="<index>",tenant="<tenant>"}`
- `capsule_tenant_resource_usage{resource="<resource>",resourcequotaindex="<index>",tenant="<tenant>"}`
When resourcequotas are configured via capsule at the Tenant scope, capacity planning is difficult via Prometheus metrics from i.e. kube-state-metrics, since the sum of the resourcequotas is not actually what's being enforced. Instead we can provide metrics that expose the aggregated resource limits and usage for a tenant.
<details>
<summary>Tenant Resource</summary>
```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
name: test
spec:
owners:
- name: alice
kind: User
namespaceOptions:
quota: 10
resourceQuotas: …
```

feat(metrics): provide metrics for tenant quotas

---

.github/workflows/releaser.yml
go.mod

Closes #1122.
@oliverbaehler I guess this should be enough to force the usage of Go v1.22.5 upon the release process. There's the option gobinary for the GoRelease build options but defining the binary location according to the version could be cumbersome and too much different from CI to local dev-env (e.g.: I'm using `gvm`).

chore: upgrade go toolchain to v1.22.5

---

docs/content/dictionary.txt
docs/content/guides/flux2-capsule.md

This PR adds a quickstart section to use the integration with Flux, with the help of the [addon](https://github.com/projectcapsule/capsule-addon-fluxcd/).
The goal is to easy the understanding and the usage of the integration, for both the platform administrator and the Tenant owner user personas.
Still, I left the previous documentation and manual setup guide to a deep dive section.

docs(guides): document fluxcd addon

---

.github/workflows/gosec.yml

Trying to solve the broken CI for the **CI gosec** workflow.
Reading the docs it seems we have to add the following options: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository

chore(ci): fixing code scanning

---

CONTRIBUTING.md
docs/content/guides/rancher-projects/capsule-rancher.md
e2e/ingress_class_networking_test.go

chore: fix some comments

---

Makefile
api/v1beta2/tenant_types.go
api/v1beta2/zz_generated.deepcopy.go
charts/capsule/crds/capsule.clastix.io_tenants.yaml
e2e/pod_runtime_class_test.go
pkg/webhook/defaults/pods.go
pkg/webhook/pod/runtimeclass.go
pkg/webhook/pod/runtimeclass_errors.go
pkg/webhook/utils/error.go

Addressing #1163 by extending the Tenant's `RuntimeClasses` specification key as we already do with Priority Class.

feat: runtimeclass default support

---

api/v1beta2/tenant_func.go
api/v1beta2/tenant_func_test.go
pkg/api/tenant_roles.go

… bindings
Found these functions to be very helpful when automating against capsule. For explenation:
With these functions we can get the subjects of a tenant (no difference in subject mapping if owner or in additionalRoleBindings) and their matching clusterRoles. This helps to translate or use tenant mapped roles to translate into other rbac implementations.

feat(api): add tenant funcs to retrieve subjects based on clusterrole bindings

---

controllers/resources/processor.go

fix: concurrent map writes when replicating namespaced objects

---

renovate.json

Since the `docs` folder contains data that must be migrated to the official documentation website, it's useless to receive notifications for outdated deps.

chore(renovate): ignore docs folder

---

charts/capsule/README.md
charts/capsule/templates/certificate.yaml
charts/capsule/values.yaml

This makes it possible to include extra variants of the service-name that aren't captured by the {{ include "capsule.fullname" }} macro

feat: Allow additional SANS for web certificate

---

.pre-commit-config.yaml
Makefile
charts/capsule/.schema.yaml
charts/capsule/values.schema.json

I have noticed a lot of users having troubles with commit messaging etc. For first time contributors they have to wait until we approve the runs again. To prevent this, i have added some pre-commit hooks which keep the semantics of files clean, check commit messages, generate helm related stuff, and lint the code. This helps users to detect errors already locally without any further action.
I have also added a schema (schema generator target) for our helm chart.

chore(repo): add pre-commit

---

controllers/tenant/namespaces.go
e2e/namespace_metadata_controller_test.go
e2e/namespace_metadata_webhook_test.go
main.go
pkg/utils/namespace_selector.go
pkg/webhook/namespace/mutation/cordoning.go
pkg/webhook/namespace/mutation/metadata.go
pkg/webhook/namespace/mutation/ownerreference.go
pkg/webhook/namespace/mutation/utils.go

Closes #1378
Sync metadata on namespace creation

feat: namespace metadata sync on creation #1378

---

.github/workflows/stale.yml

chore(workflows): update actions stale message

chore(workflows): update actions stale message

---

charts/capsule/templates/deployment.yaml
charts/capsule/templates/metrics-service.yaml

Description
This PR adds a health check port to the Helm chart's ClusterIP service definition. This enables external systems (e.g., Prometheus, Kubernetes probes) to perform liveness/readiness checks on the service more effectively.
Changes
Added health port under spec.ports in the service template.
Ensured backwards compatibility with existing deployments.
Motivation
Adding this port allows for better observability and integration with monitoring tools, and ensures the service can be properly health-checked.

feat(helm): Added health port in ClusterIP

---

charts/capsule/Chart.yaml
charts/capsule/README.md
charts/capsule/templates/crd-lifecycle/job.yaml
charts/capsule/templates/daemonset.yaml
charts/capsule/templates/deployment.yaml
charts/capsule/templates/post-install/job.yaml
charts/capsule/templates/pre-delete/job.yaml
charts/capsule/values.schema.json
charts/capsule/values.yaml

Added toggles for enabling/disabling securityContext and PodSecurityContext. If you have other security measurements in place (for example Openshift SCC's), the default SecurityContexts are not needed. In the past, we provided an empty string for the securityContext, which always worked. But suddenly, ArgoCD does not accept this anymore. So, adding a toggle for this.
(This is the same change as added in the [sops-operator](https://github.com/peak-scale/sops-operator/pull/90) and [capsule-proxy](https://github.com/projectcapsule/capsule-proxy/pull/796) )

feat: add toggle for securitycontext and podsecuritycontext
